[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "spreg"
dynamic = ["version"]
authors = [
    { name = "Luc Anselin", email = "anselin@uchicago.edu" },
    { name = "Serge Rey", email = "sjsrey@gmail.com" },
    { name = "Pedo Amaral", email = "pedrovma@gmail.com" },
]
maintainers = [{ name = "pysal contributors" }]
license = { text = "BSD 3-Clause" }
description = "PySAL Spatial Econometric Regression in Python"
keywords = [
    "spatial econometrics, regression, statistics, spatial modeling"
]
readme = { text = """\
Spatial Econometric Regression in Python"

""", content-type = "text/x-rst" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: GIS",
]
requires-python = ">=3.8"
dependencies = [
"scipy>=0.11",
"numpy>=1.23",
"pandas",
"libpysal>=4.0.0",
"scikit-learn>=0.22",
]

[project.urls]
Home = "https://github.com/pysal/spreg/"
Repository = "https://github.com/pysal/spreg"

[project.optional-dependencies]
dev = ["pre-commit"]
docs = [
    "nbsphinx",
    "numpydoc",
    "pandoc",
    "sphinx",
    "sphinxcontrib-bibtex",
    "sphinx_bootstrap_theme",
    "mkdocs-jupyter",
    "myst-parser"
]
tests = [
    "codecov",
    "coverage",
    "pytest",
    "pytest-mpl",
    "pytest-cov",
    "watermark",

]

[tool.setuptools.packages.find]
include = ["spreg", "spreg.*"]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I", "UP", "N", "B", "A", "C4", "SIM", "ARG"]
target-version = "py39"
ignore = [
    "B006",
    "B008",
    "B009",
    "B010",
    "C408",
    "E731",
    "F401",
    "F403",
    "N803",
    "N806",
    "N999",
    "UP007"
]
exclude = ["spreg/tests/*", "docs/*"]

[tool.coverage.run]
source = ["./spreg"]

[tool.coverage.report]
exclude_lines = [
    "if self.debug:",
    "pragma: no cover",
    "raise NotImplementedError",
    "except ModuleNotFoundError:",
    "except ImportError",
]
ignore_errors = true
omit = ["spreg/tests/*", "docs/conf.py"]
