 name: Build Docs
 on:
   push:
     branches:
     - master
     - main
 jobs:
   docs:
     name: CI (${{ matrix.os }}-${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     continue-on-error: ${{ matrix.experimental }}
     timeout-minutes: 20
     strategy:
       matrix:
         os: ['ubuntu-latest']
         environment-file: [ci/39.yaml]
         experimental: [false]
     defaults:
       run:
         shell: bash -l {0}
     steps:
       - uses: actions/checkout@v4
       - uses: actions/cache@v4
         env:
           CACHE_NUMBER: 0
         with:
           path: ~/conda_pkgs_dir
           key: ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles(matrix.environment-file) }}
       - uses: conda-incubator/setup-miniconda@v2
         with:
            miniconda-version: 'latest'
            channels: conda-forge
            channel-priority: true
            auto-update-conda: true
            auto-activate-base: false
            environment-file: ${{ matrix.environment-file }}
            activate-environment: test
            use-only-tar-bz2: true
       - run: conda info --all
       - run: conda list
       - run: conda config --show-sources
       - run: conda config --show
       - run: pip install -e . --no-deps --force-reinstall
       - run: cd docs; make html
       - name: Commit documentation changes
         run: |
           git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
           cp -r docs/_build/html/* gh-pages/
           cd gh-pages
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add .
           git commit -m "Update documentation" -a || true
           # The above command will fail if no changes were present, so we ignore
           # the return code.
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
            branch: gh-pages
            directory: gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN }}
            force: true
